# -*- coding: utf-8 -*-
"""polimorfismo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17qWuvRxiCrMAcHcAzC0ij8CQw9ZoNvjn
"""

# Definição das classes Funcionario, Professor e Cozinheiro
class Funcionario:
    def __init__(self, nome, salario):
        self.nome = nome
        self.salario = salario

    def trabalhar(self):
        pass


class Professor(Funcionario):
    def trabalhar(self):
        return f"Professor {self.nome} está dando aula."


class Cozinheiro(Funcionario):
    def trabalhar(self):
        return f"Cozinheiro {self.nome} está preparando a comida."


# Definição das classes Animal, Cachorro, Gato, Pássaro e Porco
class Animal:
    def __init__(self, nome):
        self.nome = nome

    def fazer_som(self):
        pass


class Cachorro(Animal):
    def fazer_som(self):
        return f"{self.nome} está latindo."


class Gato(Animal):
    def fazer_som(self):
        return f"{self.nome} está miando."


class Passaro(Animal):
    def fazer_som(self):
        return f"{self.nome} está cantando."


class Porco(Animal):
    def fazer_som(self):
        return f"{self.nome} está grunhindo."


# Definição das classes Veiculo, Caminhao, Carro e Moto
class Veiculo:
    def __init__(self, marca):
        self.marca = marca

    def mover(self):
        pass


class Caminhao(Veiculo):
    def mover(self):
        return f"O caminhão {self.marca} está transportando carga."


class Carro(Veiculo):
    def mover(self):
        return f"O carro {self.marca} está andando na estrada."


class Moto(Veiculo):
    def mover(self):
        return f"A moto {self.marca} está acelerando na pista."


# Demonstração de uso do polimorfismo
if __name__ == "__main__":
    # Uso das classes Funcionario, Professor e Cozinheiro
    funcionario1 = Professor("Ana", 5000)
    funcionario2 = Cozinheiro("Carlos", 3500)

    funcionarios = [funcionario1, funcionario2]
    for funcionario in funcionarios:
        print(funcionario.trabalhar())

    # Uso das classes Animal, Cachorro, Gato, Pássaro e Porco
    animal1 = Cachorro("Rex")
    animal2 = Gato("Mimi")
    animal3 = Passaro("Piu")
    animal4 = Porco("Babe")

    animais = [animal1, animal2, animal3, animal4]
    for animal in animais:
        print(animal.fazer_som())

    # Uso das classes Veiculo, Caminhao, Carro e Moto
    veiculo1 = Caminhao("Volvo")
    veiculo2 = Carro("Toyota")
    veiculo3 = Moto("Honda")

    veiculos = [veiculo1, veiculo2, veiculo3]
    for veiculo in veiculos:
        print(veiculo.mover())